source 'https://github.com/vokal/PrivatePodspecRepo-iOS.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod 'XcodeCoverage', '~>1.2'


target 'PeopleManagerTests', :exclusive => true do
    # Put testing-only pods here
    pod 'VOKMockUrlProtocol'
end

target 'PeopleManagerUITests', :exclusive => true do
    # Put UI-testing-only pods here
    pod 'KIF'
    pod 'VOKMockUrlProtocol'
end

